export const SCREEN_RESPONSES = {
  SEL_MENU: {
    screen: "SEL_MENU",
    data: {
      chk_tradicional: false,
      chk_chicken: false,
      chk_especial: false,
      chk_mixta: false,
      chk_do_carne: false,
      chk_cheese: false,
      chk_ranch: false,
      chk_madur: false,
      chk_pig: false,
      chk_super_flints: false,
      chk_buchona: false,
      chk_rompe: false,
      chk_mega: false,
      chk_p_trad: false,
      chk_p_trad_30: false,
      chk_p_pollo: false,
      chk_p_pollo_30: false,
      chk_p_carn: false,
      chk_p_carn_30: false,
      chk_p_mixto: false,
      chk_p_mixto_30: false,
      chk_p_esp: false,
      chk_p_esp_30: false,
      chk_chori_esp: false,
      chk_chori_esp_30: false,
      chk_p_ame: false,
      chk_p_ame_30: false,
      chk_p_flints: false,
      chk_p_flints_30: false,
      chk_p_sup: false,
      chk_p_sup_30: false,
      chk_pa_pollo: false,
      chk_pa_carne: false,
      chk_pa_mix: false,
      chk_pa_ranch: false,
      chk_pa_super: false,
      chk_des_pollo: false,
      chk_des_carne: false,
      chk_des_mixto: false,
      chk_des_super: false,
      chk_salchipapa: false,
      chk_choripapa: false,
      chk_choripollo: false,
      chk_choricarne: false,
      chk_choriloco_super: false,
      chk_choriloco_grande: false,
      chk_papaslocas_p: false,
      chk_papaslocas_m: false,
      chk_papaslocas_g: false,
      chk_picada_p: false,
      chk_picada_m: false,
      chk_picada_g: false,
      chk_pechuga_pla: false,
      chk_carne_pla: false,
      chk_pa_bur: false,
      chk_pa_bur_pollo: false,
      chk_pa_bur_carne: false,
      chk_pa_bur_super: false,
    },
  },

  CANTIDADES: {
    screen: "CANTIDADES",
    data: {
      chk_tradicional: false,
      chk_chicken: false,
      chk_especial: false,
      chk_mixta: false,
      chk_do_carne: false,
      chk_cheese: false,
      chk_ranch: false,
      chk_madur: false,
      chk_pig: false,
      chk_super_flints: false,
      chk_buchona: false,
      chk_rompe: false,
      chk_mega: false,
      chk_p_trad: false,
      chk_p_trad_30: false,
      chk_p_pollo: false,
      chk_p_pollo_30: false,
      chk_p_carn: false,
      chk_p_carn_30: false,
      chk_p_mixto: false,
      chk_p_mixto_30: false,
      chk_p_esp: false,
      chk_p_esp_30: false,
      chk_chori_esp: false,
      chk_chori_esp_30: false,
      chk_p_ame: false,
      chk_p_ame_30: false,
      chk_p_flints: false,
      chk_p_flints_30: false,
      chk_p_sup: false,
      chk_pa_pollo: false,
      chk_pa_carne: false,
      chk_pa_mix: false,
      chk_pa_ranch: false,
      chk_pa_super: false,
      chk_des_pollo: false,
      chk_des_carne: false,
      chk_des_mixto: false,
      chk_des_super: false,
      chk_salchipapa: false,
      chk_choripapa: false,
      chk_choripollo: false,
      chk_choricarne: false,
      chk_choriloco_super: false,
      chk_choriloco_grande: false,
      chk_papaslocas_p: false,
      chk_papaslocas_m: false,
      chk_papaslocas_g: false,
      chk_picada_p: false,
      chk_picada_m: false,
      chk_picada_g: false,
      chk_pechuga_pla: false,
      chk_carne_pla: false,
      chk_pa_bur: false,
      chk_pa_bur_pollo: false,
      chk_pa_bur_carne: false,
      chk_pa_bur_super: false,
    },
  },

  ADICIONALES: {
    screen: "ADICIONALES",
    data: {
      chk_ad_papam: false,
      chk_ad_papag: false,
      chk_ad_tocineta: false,
      chk_ad_taj_que: false,
      chk_ad_cho: false,
      chk_ad_hue_cod: false,
      chk_ad_aro_ceb: false,
      chk_ad_que_cos: false,
      chk_ad_sal: false,
      chk_ad_sal_ame: false,
      chk_ad_maiz: false,
    },
  },

  BEBIDAS: {
    screen: "BEBIDAS",
    data: {
      chk_gra_limon: false,
      chk_gra_naranja: false,
      chk_gra_mandarina: false,
      chk_gra_maracuya: false,
      chk_gra_yerba: false,
      chk_nat_mora: false,
      chk_nat_fresa: false,
      chk_nat_gua: false,
      chk_nat_uva: false,
      chk_cerezada: false,
      chk_maracumango: false,
    },
  },

  FINAL: {
    screen: "FINAL",
    data: {},
  },

  MET_ENTREGA: {
    screen: "MET_ENTREGA",
    data: {},
  },

  SUCCESS: {
    screen: "SUCCESS",
    data: {
      extension_message_response: {
        params: {
          flow_token: "REPLACE_FLOW_TOKEN",
          some_param_name: "PASS_CUSTOM_VALUE",
        },
      },
    },
  },
};
